export const SET_BACKGROUND_FRAME = 'SET_BACKGROUND_FRAME';
export const SET_COMPARISON_QUALITY = 'SET_COMPARISON_QUALITY';
export const CHANGE_SETTING = 'CHANGE_SETTING';
export const TAKE_SCREENSHOT = 'TAKE_SCREENSHOT';
export const TOGGLE_RECORDING = 'TOGGLE_RECORDING';
export const INITIATE_CORE = 'INITIATE_CORE';
